---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: imolein/luarocks:5.4
    commands:
      - luarocks install luacheck
      - luacheck wmia.lua

  - name: publish-docker
    image: plugins/docker
    settings:
      repo: imolein/wmia
      username:
        from_secret: docker_username
      auth:
        from_secret: docker_token
      tags:
        - latest
        - '0.3'
    when:
      event:
        - tag
      status:
        - success
    depends_on:
      - lint

trigger:
  refs:
    - refs/heads/master

---
kind: pipeline
type: docker
name: weekly-rebuild

steps:
  - name: publish-docker
    image: plugins/docker
    settings:
      repo: imolein/wmia
      username:
        from_secret: docker_username
      auth:
        from_secret: docker_token
      tags:
        - latest
        - '0.3'


trigger:
  event:
    - cron
  cron:
    - weekly_rebuild
